version: '3'
services:
  apigateway:
    image: nginx:1.15
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/www/data/index.html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webapp

  webapp:
    image: nginx:1.15